### ISSUE TITLE
Broken tests from CurationNote 'Created by API User'

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1259]
After merging in the main branch, now my test always fails at this.

The plce that triggers it is one of the pieces of new code added about adding a curation note from this line `# ./stash/stash_api/app/models/stash_api/dataset_parser.rb:29:in `parse'`.

It doesn't happen locally, but now seems to happen all the time on Github actions so our tests consistently fail.

```
Failures:

  1) StashApi::DatasetParser identifier handling updates an existing dataset with a new in-progress version
     Failure/Error: @stash_identifier = dp.parse
     
     ArgumentError:
       Value cannot be empty or nil
     # ./stash/stash-merritt/lib/datacite/mapping/datacite_xml_factory.rb:48:in `new'
     # ./stash/stash-merritt/lib/datacite/mapping/datacite_xml_factory.rb:48:in `build_resource'
     # ./stash/stash-merritt/lib/stash/merritt/builders/merritt_datacite_builder.rb:37:in `dc4_resource'
     # ./stash/stash-merritt/lib/stash/merritt/builders/merritt_datacite_builder.rb:27:in `build_xml'
     # ./stash/stash_engine/lib/stash/repo/validating_xml_builder.rb:18:in `contents'
     # ./stash/stash_engine/lib/stash/doi/id_gen.rb:51:in `update_identifier_metadata!'
     # ./stash/stash_engine/app/models/stash_engine/curation_activity.rb:169:in `submit_to_datacite'
     # ./stash/stash_api/app/models/stash_api/dataset_parser.rb:29:in `parse'
     # ./spec/models/stash_api/dataset_parser_spec.rb:322:in `block (3 levels) in <module:StashApi>'
```
