### ISSUE TITLE
Setup and configuration of Merritt-Production collection for Dryad

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#320]
- [ ] Dryad needs a collection in Merritt production
  - [ ] configured appropriately and using the S3 storage buckets supplied by @ryscher 
  - [ ] submissions should make their way to the OAI-PMH feed for harvesting.
- [ ] When collection information known, enter it into the proper tenant environment in the Rails app.

It may be that this is already done, don't know the status.

**Comment by elopatin-uc3** [comment]
@sfisher The corresponding PT ticket for Merritt is:
https://www.pivotaltracker.com/story/show/159479971

[Collection information that we have currently:](https://docs.google.com/spreadsheets/d/1OqDOc3xCs7IcBU8UE0kkGH1rWFqd7R7ouyEf2nVuxNM/edit#gid=0)

**Comment by elopatin-uc3** [comment]
System object and LDAP setup underway, and will be completed on 5/31.

**Comment by elopatin-uc3** [comment]
@sfisher just circling back to note the production collection has been set up. Work on the associated PT ticket is complete.

**Comment by sfisher** [comment]
Thanks for getting this set up, @elopatin-uc3 

Can you send me the information for this collection where it has *fill_me_in* below?  (Send the password outside of this ticket.)

```
  repository:
    domain: merritt.cdlib.org
    endpoint: "http://uc3-mrtsword-prd.cdlib.org:39001/mrtsword/collection/fill_me_in"
    username: "fill_me_in"
    password: "fill_me_in"
```

I also need information on the *set* name under which these items will appear in the OAI-PMH feed.  Often that is similar to the collection name but it isn't always exactly the same, so that is set up manually somewhere by Merritt, I think.

Thanks again.

**Comment by elopatin-uc3** [comment]
@sfisher I'm checking in with David Loy and Mark about these bits. I don't know them offhand. Will follow up when I have more info.

**Comment by elopatin-uc3** [comment]
Setting up a dryad_submitter person account in LDAP now.

**Comment by elopatin-uc3** [comment]
Now that the dryad_submitter person account is set up in LDAP, I believe what you're looking for is available @sfisher:

```
  repository:
    domain: merritt.cdlib.org
    endpoint: "http://uc3-mrtsword-prd.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: "dryad_submitter"
    password: "..."
```
