### ISSUE TITLE
Install & configure OAI-PMH notifier on UI Server

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#326]
- [x] Manually install the notifier script on the UI server
- [x] Configure it for Merritt production OAI-PMH feed reading
- [x] Configure it to only read items from the Dryad collection
- [x] Modify our current Dash service and the harvester so that it doesn't read all production collections and only the ones we have enabled in Dash and ignores the Dryad collection in the feed.
- [x] (Jim) Add the cron job to run the notifier every 5 minutes on the server

**Comment by jimvanderveen** [comment]
Okay for me to proceed on the cron job task, @sfisher ? Or do you need to finish modifying it as Dryad-only first?

**Comment by sfisher** [comment]
I still need to get the collection information from the Merritt folks.  I'll check with them before it will work.  You can cron it if you want, but it will not do anything yet since it will query for the 'fill_me_in' collection every 5 minutes.

```
migration:
  <<: *defaults
  update_base_url: https://dryad-migration.cdlib.org/stash/dataset
  oai_base_url: http://uc3-mrtoai-prd.cdlib.org:37001/mrtoai/oai/v2
  sets:
    - fill_me_in
```
